schemaVersion: 2.0.0

commandTests:
  - name: "sha256sum installation"
    command: "which"
    args: ["sha256sum"]
    expectedOutput: ["/usr/bin/sha256sum\n"]

  - name: "aws cli installation"
    command: "aws"
    args: ["--version"]
    expectedOutput: ["aws-cli/1.16.174 Python/2.7.16 Linux/3.10.0-957.12.1.el7.x86_64 botocore/1.12.164"]