language: python

services:
  - docker

install:
  - docker-compose build
  on:
    branch: master
  - curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && chmod +x container-structure-test-linux-amd64 && sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test

script:
  - bash run_tests.sh

before_deploy:
  - pip install awscli
  - aws ecr get-login --no-include-email | bash

deploy:
  provider: script
  script: bash deploy_images.sh dev
  on:
    branch: tkAddS3BucketAsConfig
