version: "3"
services:
  clamav:
    image: "nationalarchives/tdr-virus-check:dev"
    build:
      context: ./virus
    container_name: clamav
  siegfried:
    image: "nationalarchives/tdr-file-format-check:dev"
    build:
      context: ./fileformat
    container_name: siegfried
  checksum:
    image: "nationalarchives/tdr-checksum-check:dev"
    build:
      context: ./checksum
    container_name: checksum
