version: "3"
services:
  clamav:
    image: nationalarchives/tdr-virus-check
    build:
      context: ./virus
      args:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_DEFAULT_REGION
    container_name: clamav
  siegfried:
    image: nationalarchives/tdr-file-format-check
    build:
      context: ./fileformat
      args:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_DEFAULT_REGION
    container_name: siegfried
  checksum:
    image: nationalarchives/tdr-checksum-check
    build:
      context: ./checksum
      args:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_DEFAULT_REGION
    container_name: checksum
