schemaVersion: 2.0.0

commandTests:
  - name: "siegfried installation"
    command: "which"
    args: ["sf"]
    expectedOutput: ["/usr/bin/sf\n"]

  - name: "aws cli installation"
    command: "aws"
    args: ["--version"]
    exitCode: 0

#metadataTest:
#  env:
#    - key: AWS_DEFAULT_REGION
#      value: "eu-west-2"