schemaVersion: 2.0.0

commandTests:
  - name: "clamav installation"
    command: "which"
    args: ["clamscan"]
    expectedOutput: ["/usr/bin/clamscan\n"]

  - name: "aws cli installation"
    command: "aws"
    args: ["--version"]
    exitCode: 0

